services:
  app:
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
  worker:
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run worker
