export const scenarios = [
  "At a concert or music event",
  "At a conference or business meeting",
  "At a funeral or memorial service",
  "At a hotel",
  "At a museum or art gallery",
  "At a park or recreational area",
  "At a party or gathering",
  "At a religious ceremony or place of worship",
  "At a restaurant",
  "At a spa or wellness center",
  "At a sporting event or competition",
  "At a wedding or special occasion",
  "At a zoo or aquarium",
  "At home / family life",
  "At school",
  "At the airport",
  "At the bank or post office",
  "At the beach or pool",
  "At the gym or fitness center",
  "At the library or bookstore",
  "At the market or grocery store",
  "At the movies or theater",
  "Cooking and food preparation",
  "Cultural events and festivals",
  "Daily routines and chores",
  "Dating and romantic relationships",
  "Dealing with language barriers and misunderstandings",
  "Dealing with legal matters",
  "Environmental issues and sustainability",
  "Handling emergencies and accidents",
  "Hobbies and leisure activities",
  "In a classroom or lecture hall",
  "In a foreign country",
  "In a taxi or rideshare",
  "In the office",
  "Mass transit",
  "Medical emergencies and visiting a doctor",
  "Navigating a new city",
  "On a farm or in rural areas",
  "On a road trip or adventure",
  "Shopping and fashion",
  "Socializing and making friends",
  "Sports and exercise",
  "Studying or working abroad",
  "The great outdoors",
  "Traveling and sightseeing",
  "Using technology and devices",
  "Volunteering and community service",
  "Weather and seasons",
];
