ALTER TABLE "UserSettings"
ADD COLUMN "readerBookFontSize" INTEGER NOT NULL DEFAULT 20,
ADD COLUMN "readerBookLineHeight" DOUBLE PRECISION NOT NULL DEFAULT 1.75,
ADD COLUMN "readerBookColumnWidth" INTEGER NOT NULL DEFAULT 800;
